// Mocks generated by Mockito 5.4.6 from annotations
// in sport_matcher/test/data/device_id/persistence/database/device_id_database_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences_platform_interface/shared_preferences_platform_interface.dart'
    as _i2;
import 'package:shared_preferences_platform_interface/types.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SharedPreferencesStorePlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesStorePlatform extends _i1.Mock
    implements _i2.SharedPreferencesStorePlatform {
  MockSharedPreferencesStorePlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isMock =>
      (super.noSuchMethod(Invocation.getter(#isMock), returnValue: false)
          as bool);

  @override
  _i3.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setValue(String? valueType, String? key, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#setValue, [valueType, key, value]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clearWithPrefix(String? prefix) =>
      (super.noSuchMethod(
            Invocation.method(#clearWithPrefix, [prefix]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clearWithParameters(_i4.ClearParameters? parameters) =>
      (super.noSuchMethod(
            Invocation.method(#clearWithParameters, [parameters]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, Object>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<Map<String, Object>>.value(
              <String, Object>{},
            ),
          )
          as _i3.Future<Map<String, Object>>);

  @override
  _i3.Future<Map<String, Object>> getAllWithPrefix(String? prefix) =>
      (super.noSuchMethod(
            Invocation.method(#getAllWithPrefix, [prefix]),
            returnValue: _i3.Future<Map<String, Object>>.value(
              <String, Object>{},
            ),
          )
          as _i3.Future<Map<String, Object>>);

  @override
  _i3.Future<Map<String, Object>> getAllWithParameters(
    _i4.GetAllParameters? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllWithParameters, [parameters]),
            returnValue: _i3.Future<Map<String, Object>>.value(
              <String, Object>{},
            ),
          )
          as _i3.Future<Map<String, Object>>);
}
