// Mocks generated by Mockito 5.4.6 from annotations
// in sport_matcher/test/ui/authentication/sign_up/widgets/sign_up_screen_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sport_matcher/data/auth/domain/auth_tokens.dart' as _i2;
import 'package:sport_matcher/data/auth/mapper/auth_tokens_mapper.dart' as _i11;
import 'package:sport_matcher/data/auth/network/api/auth_api.dart' as _i4;
import 'package:sport_matcher/data/auth/network/response/auth_tokens_reponse.dart'
    as _i7;
import 'package:sport_matcher/data/auth/persistence/entity/auth_tokens_entity.dart'
    as _i3;
import 'package:sport_matcher/data/auth/repository/abstract_auth_repository.dart'
    as _i10;
import 'package:sport_matcher/data/core/api_request/api_result.dart' as _i6;
import 'package:sport_matcher/data/device_id/repository/abstract_device_id_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthTokensDomain_0 extends _i1.SmartFake
    implements _i2.AuthTokensDomain {
  _FakeAuthTokensDomain_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokensEntity_1 extends _i1.SmartFake
    implements _i3.AuthTokensEntity {
  _FakeAuthTokensEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i4.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.ApiResult<_i7.AuthTokensReponse>> registerWithEmail({
    required String? email,
    required String? password,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [], {
              #email: email,
              #password: password,
              #deviceId: deviceId,
            }),
            returnValue: _i5.Future<_i6.ApiResult<_i7.AuthTokensReponse>>.value(
              _i8.dummyValue<_i6.ApiResult<_i7.AuthTokensReponse>>(
                this,
                Invocation.method(#registerWithEmail, [], {
                  #email: email,
                  #password: password,
                  #deviceId: deviceId,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.ApiResult<_i7.AuthTokensReponse>>);
}

/// A class which mocks [AbstractDeviceIdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractDeviceIdRepository extends _i1.Mock
    implements _i9.AbstractDeviceIdRepository {
  MockAbstractDeviceIdRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(this, Invocation.method(#getDeviceId, [])),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [AbstractAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractAuthRepository extends _i1.Mock
    implements _i10.AbstractAuthRepository {
  MockAbstractAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveTokens(_i2.AuthTokensDomain? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [tokens]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthTokensMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokensMapper extends _i1.Mock implements _i11.AuthTokensMapper {
  MockAuthTokensMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthTokensDomain responseToDomain(_i7.AuthTokensReponse? response) =>
      (super.noSuchMethod(
            Invocation.method(#responseToDomain, [response]),
            returnValue: _FakeAuthTokensDomain_0(
              this,
              Invocation.method(#responseToDomain, [response]),
            ),
          )
          as _i2.AuthTokensDomain);

  @override
  _i3.AuthTokensEntity domainToEntity(_i2.AuthTokensDomain? domain) =>
      (super.noSuchMethod(
            Invocation.method(#domainToEntity, [domain]),
            returnValue: _FakeAuthTokensEntity_1(
              this,
              Invocation.method(#domainToEntity, [domain]),
            ),
          )
          as _i3.AuthTokensEntity);
}
